### ISSUE TITLE
no mount usb in rdesktop 2.0-1.8.2-1

### ISSUE THREAD

**Issue by kvaich** [openthinclient/os-applications#15]
1.rdesktop setting rdesktop_legasy -yes
2.parameter -r disk: media = / media
3.Connect RDP windows server 2008 r2
4.start Windows Explorer - no flash
and
1.rdesktop setting rdesktop_legasy - no
2.parameter -r usbrdr
3.Connect RDP windows server 2008 r2
4.start Windows Explorer - no flash

Please correct this error

**Comment by jfrenzel** [comment]
It seems, that this is a issue of rdesktop. Please try our latest rdesktop package. May this bug is fixed in versio 1.8.3 . 

Issue closes now.
