### ISSUE TITLE
Custom Icon

### ISSUE THREAD

**Issue by frettijule** [openthinclient/os-applications#21]
If I use in launcher-formular custom-icon, the client look for that icon in (old) directory /var/tcos/custom/icons. This directory doesn't exist on the client, so that feature is not working.

[Desktop Entry]
Comment=Intranet
Name=Intranet
X-TCOS-DN=cn=Intranet,ou=apps,ou=openthinclient,dc=openthinclient,dc=org
Exec=/opt/chrome/tcos/launcher 636E3D496E7472616E65742C6F753D617070732C6F753D6F70656E7468696E636C69656E742C64633D6F70656E7468696E636C69656E742C64633D6F7267
Path=/opt/chrome
Type=Application
Categories=Application;TCOS;
Icon=/var/tcos/custom/icons/soniclogo.png

A workaround is a tgz-package included the icons in path /var/tcos/custom/icons

**Comment by jfrenzel** [comment]
This shoul not happen if you're up to date.

Please see [tcos.py](https://github.com/openthinclient/os-applications/blob/master/tcos-libs/tcos-libs-2.0/package-rootfs/usr/lib/pymodules/python2.7/pytcos/tcos.py)

[link to Google!](http://google.com)

     if app_icon_custom:
           app_icon = "/tcos/link/custom/icons/" + app_icon_custom

**Comment by frettijule** [comment]
I'm on testing-Repo, so the new update of tcos-libs wasn't listetd. 
Now it is fine. 
Best regards Thomas
