### ISSUE TITLE
tcos-scripts: Package 2.1-13 is listet in package-list, but doesn't exist

### ISSUE THREAD

**Issue by frettijule** [openthinclient/os-applications#24]
After update package-list today, a new update of tcos-scripts is listed, version 2.1.-13, also in changelog.

After trying the update, i get an error, because the deb-file is not existing in the server-directory. Please create it or update the version-number.

thanks

**Comment by jfrenzel** [comment]
Thanks for reporting this issue. We made some mistakes while merging and uploading. 
Fixed. Please update all packages. 

Regards, Jörn
