### ISSUE TITLE
What about ru localization?

### ISSUE THREAD

**Issue by lcfm1** [openthinclient/os-applications#27]
How i can add localization?

**Comment by steffenhoenig** [comment]
Depends on what you need to be localized. language of the gui menus, keyboard mapping, dictionary.

**Comment by lcfm1** [comment]
@steffenhoenig,  all gui localization.

**Comment by jfrenzel** [comment]
@lcfm1, please feel free to add additional languaes to all the xml-files in alle the packages. Pull requests are welcome. This is not an issue so fare.
